from django.test import TestCase

from apps.accounts.models import User
from apps.customfields.models import CustomField, RequestForm, RequestFormField, TicketFieldValue
from apps.customfields.service import save_field_values
from apps.tickets.models import Ticket


class CustomFieldTests(TestCase):
    def test_key_autogenerated_and_unique(self):
        # Use a label that does not collide with the fields seeded by the
        # customfields data migration (0002_seed_forms seeds key="asset-tag").
        a = CustomField.objects.create(label="Serial Number")
        b = CustomField.objects.create(label="Serial Number")
        self.assertEqual(a.key, "serial-number")
        self.assertEqual(b.key, "serial-number-2")

    def test_choice_list(self):
        f = CustomField.objects.create(
            label="OS", field_type="dropdown", choices="macOS\nWindows\nLinux"
        )
        self.assertEqual(f.choice_list, ["macOS", "Windows", "Linux"])


class RequestFormTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user("u", "u@x.com", "p")
        self.form = RequestForm.objects.create(name="Hardware Request")
        self.f1 = CustomField.objects.create(label="Asset", required=True)
        self.f2 = CustomField.objects.create(label="Notes", field_type="textarea")
        RequestFormField.objects.create(form=self.form, field=self.f1, order=0)
        RequestFormField.objects.create(form=self.form, field=self.f2, order=1)

    def test_slug_autogenerated(self):
        self.assertEqual(self.form.slug, "hardware-request")

    def test_ordered_fields(self):
        self.assertEqual([f.label for f in self.form.ordered_fields()], ["Asset", "Notes"])

    def test_save_values_and_required(self):
        ticket = Ticket.objects.create(title="T", description="d", created_by=self.user)
        missing = save_field_values(ticket, self.form, {"cf_asset": "", "cf_notes": "hi"})
        self.assertIn("Asset", missing)
        self.assertEqual(TicketFieldValue.objects.get(ticket=ticket, field=self.f2).value, "hi")

    def test_save_values_ok(self):
        ticket = Ticket.objects.create(title="T", description="d", created_by=self.user)
        missing = save_field_values(ticket, self.form, {"cf_asset": "LT-42", "cf_notes": ""})
        self.assertEqual(missing, [])
        self.assertEqual(TicketFieldValue.objects.get(ticket=ticket, field=self.f1).value, "LT-42")
