# Generated by Django 5.2.16 on 2026-07-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
        ('tickets', '0005_ticket_due_at_ticket_first_responded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('key', models.SlugField(blank=True, max_length=140, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('number', 'Number'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('date', 'Date')], default='text', max_length=20)),
                ('choices', models.TextField(blank=True, default='', help_text='One option per line (for dropdown fields).')),
                ('help_text', models.CharField(blank=True, default='', max_length=200)),
                ('required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('intro', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customfields.customfield')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='customfields.requestform')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('form', 'field')},
            },
        ),
        migrations.AddField(
            model_name='requestform',
            name='fields',
            field=models.ManyToManyField(blank=True, through='customfields.RequestFormField', to='customfields.customfield'),
        ),
        migrations.CreateModel(
            name='TicketFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customfields.customfield')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='tickets.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'field')},
            },
        ),
    ]
