# Generated by Django 5.2.16 on 2026-07-10 00:04

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.JackilUserManager()),
            ],
        ),
    ]
