# Generated by Django 5.2.16 on 2026-07-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, default='', help_text='Base64-encoded profile image data URI'),
        ),
    ]
