# Generated by Django 5.2.16 on 2026-07-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default schedule', max_length=100)),
                ('mode', models.CharField(choices=[('24_7', '24 / 7'), ('business', 'Business hours')], default='24_7', max_length=10)),
                ('workday_start', models.TimeField(default='09:00')),
                ('workday_end', models.TimeField(default='17:00')),
                ('workdays', models.CharField(default='0,1,2,3,4', help_text='Comma weekday ints, Mon=0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLATarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, unique=True)),
                ('response_minutes', models.PositiveIntegerField(default=240)),
                ('resolution_minutes', models.PositiveIntegerField(default=1440)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
