# Generated by Django 5.2.16 on 2026-07-09 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('imap_host', models.CharField(blank=True, default='', max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_username', models.CharField(blank=True, default='', max_length=255)),
                ('imap_password', models.CharField(blank=True, default='', max_length=255)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('imap_folder', models.CharField(default='INBOX', max_length=120)),
                ('signature', models.TextField(blank=True, default='')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_poll_status', models.CharField(blank=True, default='', max_length=255)),
                ('last_seen_uid', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'inboxes',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
