# Generated by Django 5.2.16 on 2026-07-09 04:34

import apps.tickets.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_assigned_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requester_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('api', 'API')], default='web', max_length=10),
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reply', 'Reply'), ('note', 'Internal note'), ('incoming_email', 'Incoming email'), ('outgoing_email', 'Outgoing email'), ('system', 'System event')], default='reply', max_length=20)),
                ('body', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=True)),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('to_email', models.CharField(blank=True, default='', max_length=255)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=255)),
                ('email_status', models.CharField(blank=True, choices=[('', '—'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='', max_length=10)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.tickets.models.attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticketmessage')),
            ],
        ),
    ]
