# Generated by Django 5.2.16 on 2026-07-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_savedview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketComment',
        ),
    ]
