# Generated by Django 5.2.16 on 2026-07-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_delete_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
