from django.test import TestCase

from apps.kb.models import KBArticle, KBCategory
from apps.kb.service import (
    public_categories,
    published_articles,
    record_view,
    search_articles,
)


class KBCategoryModelTest(TestCase):
    def test_category_slug_autogenerated(self):
        cat = KBCategory(name="Test Category")
        cat.save()
        self.assertEqual(cat.slug, "test-category")


class KBArticleModelTest(TestCase):
    def test_article_slug_unique(self):
        cat = KBCategory.objects.create(name="Test", slug="test")
        a1 = KBArticle.objects.create(category=cat, title="Reset Password", body="a")
        a2 = KBArticle.objects.create(category=cat, title="Reset Password", body="b")
        self.assertTrue(a1.slug.startswith("reset-password"))
        self.assertTrue(a2.slug.startswith("reset-password"))
        self.assertNotEqual(a1.slug, a2.slug)


class KBServiceTest(TestCase):
    @classmethod
    def setUpTestData(cls):
        cat = KBCategory.objects.create(name="Cat", slug="cat")
        cls.public_article = KBArticle.objects.create(
            category=cat,
            title="VPN Setup Guide",
            slug="vpn-setup-guide",
            body="How to set up your VPN connection.",
            is_published=True,
            is_public=True,
        )
        cls.private_article = KBArticle.objects.create(
            category=cat,
            title="Internal Policy",
            slug="internal-policy",
            body="This is for internal use only.",
            is_published=True,
            is_public=False,
        )
        cls.unpublished_article = KBArticle.objects.create(
            category=cat,
            title="Draft Article",
            slug="draft-article",
            body="This is a draft.",
            is_published=False,
            is_public=True,
        )

    def test_public_categories(self):
        categories = list(public_categories())
        self.assertTrue(len(categories) >= 1)
        self.assertTrue(any(c.name == "Cat" for c in categories))

    def test_search_matches_title_and_body(self):
        results = search_articles("vpn")
        self.assertTrue(results.filter(pk=self.public_article.pk).exists())

    def test_published_articles_excludes_unpublished(self):
        results = published_articles()
        self.assertFalse(results.filter(pk=self.unpublished_article.pk).exists())

    def test_public_only_filter(self):
        results_public = published_articles(public_only=True)
        self.assertFalse(results_public.filter(pk=self.private_article.pk).exists())

        results_all = published_articles(public_only=False)
        self.assertTrue(results_all.filter(pk=self.private_article.pk).exists())

    def test_record_view_increments(self):
        self.assertEqual(self.public_article.views, 0)
        record_view(self.public_article)
        self.public_article.refresh_from_db()
        self.assertEqual(self.public_article.views, 1)
