# Generated by Django 5.2.16 on 2026-07-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Jackil', max_length=60)),
                ('tagline', models.CharField(default='IT Ticket Management', max_length=120)),
                ('accent', models.CharField(default='lavender', max_length=20)),
            ],
        ),
    ]
