# Generated by Django 5.2.16 on 2026-07-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteBranding',
        ),
    ]
